package tools_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/openclaw/openclaw-go/internal/tools"
)

func TestEngine_ExecBash(t *testing.T) {
	tmpDir := t.TempDir()
	eng, err := tools.NewEngine(tmpDir)
	if err != nil {
		t.Fatalf("failed to create engine: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	// Test Bash exec creation of file
	_, err = eng.ExecBash(ctx, "echo 'hello world' > test.txt")
	if err != nil {
		t.Fatalf("bash exec failed: %v", err)
	}

	// Verify file is in workspace
	data, err := os.ReadFile(filepath.Join(tmpDir, "test.txt"))
	if err != nil {
		t.Fatalf("could not read file generated by bash: %v", err)
	}

	if strings.TrimSpace(string(data)) != "hello world" {
		t.Errorf("expected 'hello world', got '%s'", string(data))
	}

	// Test Bash exec capturing output
	out, err := eng.ExecBash(ctx, "cat test.txt")
	if err != nil {
		t.Fatalf("bash exec read failed: %v", err)
	}

	if strings.TrimSpace(out) != "hello world" {
		t.Errorf("expected output 'hello world', got '%s'", out)
	}
}

func TestEngine_FileSystemBoundaries(t *testing.T) {
	tmpDir := t.TempDir()
	eng, err := tools.NewEngine(tmpDir)
	if err != nil {
		t.Fatalf("failed to create engine: %v", err)
	}

	// Test valid file operations
	err = eng.WriteFile("src/main.js", "console.log('hi');")
	if err != nil {
		t.Fatalf("write file failed: %v", err)
	}

	content, err := eng.ReadFile("src/main.js")
	if err != nil {
		t.Fatalf("read file failed: %v", err)
	}

	if content != "console.log('hi');" {
		t.Errorf("content mismatch, got: %s", content)
	}

	// Test path traversal payload - WRITE
	err = eng.WriteFile("../evil.txt", "muahaha")
	if err == nil {
		t.Fatal("expected directory traversal attempt to be blocked during WriteFile, but it succeeded")
	}

	if !strings.Contains(err.Error(), "security violation") {
		t.Errorf("expected security violation error, got: %v", err)
	}

	// Test path traversal payload - READ
	_, err = eng.ReadFile("../../../etc/passwd")
	if err == nil {
		t.Fatal("expected directory traversal attempt to be blocked during ReadFile, but it succeeded")
	}

	if !strings.Contains(err.Error(), "security violation") {
		t.Errorf("expected security violation error, got: %v", err)
	}
}
